name: Build LaTeX document, check and commit to gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: presentation.tex
    - name: Check pdf file
      run: |
        file presentation.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        set -e

        # configure git
        git config --global user.name "rosenkrands"
        git config --global user.email "krosen17@student.aau.dk"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        # Copy and commit the PDF file
        mkdir -p "$GITHUB_WORKSPACE/deploy"
        cp -f presentation.pdf "$GITHUB_WORKSPACE/deploy/presentation.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git init
        git checkout --orphan gh-pages
        git add presentation.pdf
        git commit -m "[github actions] deploy"
        git remote add origin git@github.com:rosenkrands/measure-theory-exam.git
        git push --force --set-upstream origin gh-pages
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
